site_name: uftrace

theme:
  name: readthedocs

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        ko: 한국어

nav:
  - Home:
    - en: en/uftrace.md
    - ko: ko/uftrace.md